### PR TITLE
Fix the bug with unrecorded session

### LINKED ISSUE #238: Unrecorded external session
## Description
We have a bug with session recording, it works time to time.

## Expected behavior
It should record session every time.

## Actual behavior
Sometimes vision-sdk doesn't create session files after calling `startRecording`

## Configuration
 - Device: iPhoneX
 - OS: iOS11.4
 - Frameworks versions (leave the ones you're using):
   - MapboxVisionNative [e.g. 0.9.0]
   - MapboxVision [e.g. 0.9.0]

## Additional context
The screenshot was made with `DataRecorder` which creates folders by itself that is why zero folders are visible. In common case when we call `startRecording(to path:)` we expect `VisionManager` will create folder.

### PR DESCRIPTION
**Pull request by IodaMikeMapbox**
Checks:

* [x] Update changelog
* [x] Rebase to `dev` branch
* [x] Assign reviewers

Linked issues:
Resolves #238

### CODE REVIEW

File: MapboxVision/Services/Recording/RecordCoordinator.swift [hunk 1]
```diff
@@ -33,7 +33,14 @@ final class RecordCoordinator {
...
     private var trimRequestCache = [Int: [VideoTrimRequest]]()
-    private(set) var isRecording: Bool = false
+    var isRecording: Bool {
+        var result = false
+        processingQueue.sync {
+            result = _isRecording
+        }
+        return result
+    }
+    private var _isRecording: Bool = false
```
Comment (dersim-davaod) [inline MapboxVision/Services/Recording/RecordCoordinator.swift]: Can we try to rename it to avoid `_` prefix? Generally I'm ok with it, but would prefer to avoid.
Probably something like `isRecordingState` or `isRecordingInternal`?

File: MapboxVision/Services/Recording/RecordCoordinator.swift [hunk 2]
```diff
@@ -33,7 +33,14 @@ final class RecordCoordinator {
     }
 
     private var trimRequestCache = [Int: [VideoTrimRequest]]()
-    private(set) var isRecording: Bool = false
+    var isRecording: Bool {
```
Comment (dersim-davaod) [inline MapboxVision/Services/Recording/RecordCoordinator.swift]: nit: Can we simplify it to:

```suggestion
    var isRecording: Bool {
        return processingQueue.sync {
            _isRecording
        }
    }
```

?

File: MapboxVision/Services/Recording/RecordCoordinator.swift (hunk 1 above)
Comment (IodaMikeMapbox) [reply MapboxVision/Services/Recording/RecordCoordinator.swift]: sure

File: MapboxVision/Services/Recording/RecordCoordinator.swift (hunk 2 above)
Comment (IodaMikeMapbox) [reply MapboxVision/Services/Recording/RecordCoordinator.swift]: nice, didn't know swift can do that, will change

File: MapboxVision/Services/Recording/RecordCoordinator.swift (hunk 1 above)
Comment (IodaMikeMapbox) [reply MapboxVision/Services/Recording/RecordCoordinator.swift]: done

File: MapboxVision/Services/Recording/RecordCoordinator.swift (hunk 2 above)
Comment (IodaMikeMapbox) [reply MapboxVision/Services/Recording/RecordCoordinator.swift]: done

**Comment by IodaMikeMapbox** [comment]
@dersim-davaod PTAL at the last commit

File: MapboxVision/Services/Recording/RecordCoordinator.swift [hunk 3]
```diff
@@ -96,104 +101,130 @@ final class RecordCoordinator {
...
     func stopRecording() {
-        guard isRecording, isReady else { return }
-
-        stopRecordingInBackgroundTask = UIApplication.shared.beginBackgroundTask()
-
         processingQueue.async { [weak self] in
-            guard let self = self else { return }
+            guard let self = self, self.isRecordingInternal, self.isReady else { return }
+
+            self.stopRecordingInBackgroundTask = UIApplication.shared.beginBackgroundTask()
```
Comment (chezzdev) [inline MapboxVision/Services/Recording/RecordCoordinator.swift]: Could you please check that after moving this to async block it will still be called before suspending execution.
If you're testing it with Teaser please make sure to disable background mode "location updates".

Comment (IodaMikeMapbox) [reply MapboxVision/Services/Recording/RecordCoordinator.swift]: yep

**Comment by IodaMikeMapbox** [comment]
@chezzdev @dersim-davaod  Please check the just added video clipping test

File: MapboxVisionTests/Mocks/FakeVideoSource.swift [hunk 4]
```diff
@@ -0,0 +1,94 @@
...
+        let status = CVPixelBufferCreate(kCFAllocatorDefault, Int(Constants.frameWidth), Int(Constants.frameWidth), kCVPixelFormatType_32BGRA, attrs, &pixelBuffer)
+        guard status == kCVReturnSuccess else {
+            return nil
+        }
+
+        CVPixelBufferLockBaseAddress(pixelBuffer!, CVPixelBufferLockFlags(rawValue: 0))
+        let pixelData = CVPixelBufferGetBaseAddress(pixelBuffer!)
+
+        let rgbColorSpace = CGColorSpaceCreateDeviceRGB()
+        let context = CGContext(data: pixelData, width: Int(Constants.frameWidth), height: Int(Constants.frameHeight), bitsPerComponent: Constants.bitsInByte, bytesPerRow: CVPixelBufferGetBytesPerRow(pixelBuffer!), space: rgbColorSpace, bitmapInfo: CGImageAlphaInfo.noneSkipFirst.rawValue)
```
Comment (chezzdev) [inline MapboxVisionTests/Mocks/FakeVideoSource.swift]: Please reformat the line.

Comment (chezzdev) [reply MapboxVisionTests/Mocks/FakeVideoSource.swift]: No need for `Int` cast.

File: MapboxVisionTests/RecordCoordinatorTests.swift [hunk 5]
```diff
@@ -72,6 +70,69 @@ final class RecordCoordinatorTests: XCTestCase {
...
+        let start: Float
+        let end: Float
+
+        init(start: Float, end: Float) {
+            self.start = start
+            self.end = end
+        }
+    }
+
+    func testVideoClipping(withRequests requests: [TestClipRequest], _ message: String = "", line: UInt = #line) {
```
Comment (chezzdev) [inline MapboxVisionTests/RecordCoordinatorTests.swift]: Let's keep the naming convention (`test*`) for test-cases only.
```suggestion
    private func performVideoClipping(with requests: [TestClipRequest], _ message: String = "", line: UInt = #line) {
```
Also what's the point in `line` argument? Don't we want to know where exactly assert failed instead of where this function was called?

File: MapboxVisionTests/RecordCoordinatorTests.swift [hunk 6]
```diff
@@ -72,6 +70,69 @@ final class RecordCoordinatorTests: XCTestCase {
...
+        let expectation = XCTestExpectation(description: "Wait for a big enough amount of time for record processing queue to finish its job")
+        let videoSource = FakeVideoSource()
+        videoSource.add(observer: coordinator)
+        videoSource.start()
+        coordinator.startRecording(referenceTime: 0, videoSettings: videoSettings) {}
+        _ = Timer.scheduledTimer(withTimeInterval: 4.0, repeats: false) { _ in
+            print("Make \(requests.count) clip\(requests.count == 1 ? "" : "s")")
```
Comment (chezzdev) [inline MapboxVisionTests/RecordCoordinatorTests.swift]: Please remove all prints from the function.

File: MapboxVisionTests/RecordCoordinatorTests.swift [hunk 7]
```diff
@@ -72,6 +70,69 @@ final class RecordCoordinatorTests: XCTestCase {
...
+        let end: Float
+
+        init(start: Float, end: Float) {
+            self.start = start
+            self.end = end
+        }
+    }
+
+    func testVideoClipping(withRequests requests: [TestClipRequest], _ message: String = "", line: UInt = #line) {
+        let expectation = XCTestExpectation(description: "Wait for a big enough amount of time for record processing queue to finish its job")
```
Comment (chezzdev) [inline MapboxVisionTests/RecordCoordinatorTests.swift]:
```suggestion
        let expectation = XCTestExpectation(description: "All the requested clips are successfully cut")
```
Is it what we really expecting?

File: MapboxVisionTests/RecordCoordinatorTests.swift [hunk 8]
```diff
@@ -72,6 +70,69 @@ final class RecordCoordinatorTests: XCTestCase {
...
+            print("Make \(requests.count) clip\(requests.count == 1 ? "" : "s")")
+            requests.forEach {
+                self.coordinator.makeClip(from: $0.start, to: $0.end)
+            }
+
+            _ = Timer.scheduledTimer(withTimeInterval: 1.0, repeats: false) { _ in
+                self.coordinator.stopRecording()
+
+                _ = Timer.scheduledTimer(withTimeInterval: 1.0, repeats: false) { _ in
+                    let path = "\(DocumentsLocation.currentRecording.path)"
```
Comment (chezzdev) [inline MapboxVisionTests/RecordCoordinatorTests.swift]: It's already a string, no need for interpolation.

File: MapboxVisionTests/RecordCoordinatorTests.swift [hunk 9]
```diff
@@ -72,6 +70,69 @@ final class RecordCoordinatorTests: XCTestCase {
...
+                    let directoryContent = (try? FileManager.default.contentsOfDirectory(at: URL(string: path)!, includingPropertiesForKeys: nil, options: []))
```
Comment (chezzdev) [inline MapboxVisionTests/RecordCoordinatorTests.swift]: Why using braces?

File: MapboxVisionTests/RecordCoordinatorTests.swift [hunk 10]
```diff
@@ -72,6 +70,69 @@ final class RecordCoordinatorTests: XCTestCase {
...
+
+                    if let directoryContent = directoryContent {
+                        for file in directoryContent {
+                            print("File \(file)")
+                            if file.hasDirectoryPath {
+                                let subDirectoryContent = (try? FileManager.default.contentsOfDirectory(at: file, includingPropertiesForKeys: nil, options: []))
+                                if let subDirectoryContent = subDirectoryContent {
+                                    let numberOfVideos = subDirectoryContent.filter {
+                                        $0.pathExtension == "mp4"
```
Comment (chezzdev) [inline MapboxVisionTests/RecordCoordinatorTests.swift]: Video file type can be taken from `videoSettings.fileExtension`.

File: MapboxVisionTests/RecordCoordinatorTests.swift [hunk 11]
```diff
@@ -72,6 +70,69 @@ final class RecordCoordinatorTests: XCTestCase {
...
+                                }
+                            }
+                        }
+                    }
+                    expectation.fulfill()
+                }
+            }
+        }
+
+        XCTWaiter().wait(for: [expectation], timeout: 20.0)
```
Comment (chezzdev) [inline MapboxVisionTests/RecordCoordinatorTests.swift]: What's the typical execution time for such test? I guess we could reduce the timeout significantly, 10 sec at least.

File: MapboxVisionTests/RecordCoordinatorTests.swift [hunk 12]
```diff
@@ -97,3 +158,9 @@ extension RecordCoordinatorTests: RecordCoordinatorDelegate {
         recordingStoppedExpectation.fulfill(with: recordingPath)
     }
 }
+
+extension RecordCoordinator: VideoSourceObserver {
+    public func videoSource(_ videoSource: VideoSource, didOutput videoSample: VideoSample) {
+        self.handleFrame(videoSample.buffer)
```
Comment (chezzdev) [inline MapboxVisionTests/RecordCoordinatorTests.swift]:
```suggestion
        handleFrame(videoSample.buffer)
```

File: MapboxVisionTests/Mocks/FakeVideoSource.swift [hunk 13]
```diff
@@ -0,0 +1,105 @@
...
+        let cgImage = context.createCGImage(cmage, from: cmage.extent)!
+        let image = UIImage(cgImage: cgImage)
+        return image
+    }
+
+    func makePixelBuffer() -> CVPixelBuffer? {
+        let attrs = [
+            kCVPixelBufferCGImageCompatibilityKey: kCFBooleanTrue,
+            kCVPixelBufferCGBitmapContextCompatibilityKey: kCFBooleanTrue,
+            kCVPixelBufferOpenGLESCompatibilityKey: kCFBooleanTrue,
```
[the remark this answers is not in the document]
Comment (IodaMikeMapbox) [reply MapboxVisionTests/Mocks/FakeVideoSource.swift]: yes

File: MapboxVisionTests/Mocks/FakeVideoSource.swift [hunk 14]
```diff
@@ -0,0 +1,94 @@
...
+    func start() {
+        timer.resume()
+    }
+
+    func stop() {
+        timer.suspend()
+    }
+
+    @objc
+    func emitNewBuffer() {
```
[the remark this answers is not in the document]
Comment (IodaMikeMapbox) [reply MapboxVisionTests/Mocks/FakeVideoSource.swift]: yes

File: MapboxVisionTests/Mocks/FakeVideoSource.swift [hunk 15]
```diff
@@ -0,0 +1,105 @@
+import Foundation
+
+@testable import MapboxVision
+
+class FakeVideoSource: ObservableVideoSource {
```
[the remark this answers is not in the document]
Comment (IodaMikeMapbox) [reply MapboxVisionTests/Mocks/FakeVideoSource.swift]: done

File: MapboxVisionTests/Mocks/FakeVideoSource.swift [hunk 16]
```diff
@@ -0,0 +1,105 @@
...
+        static let fps: Int32 = 30
+        static let frameDelay = 1.0 / Double(fps)
+        static let frameWidth = 960
+        static let frameHeight = 540
+        static let bitsInByte = 8
+    }
+
+    private let processingQueue = DispatchQueue(label: "com.mapbox.RecordCoordinatorTest.VideoSource")
+    private lazy var timer: DispatchSourceTimer = {
+        let t = DispatchSource.makeTimerSource()
```
[the remark this answers is not in the document]
Comment (IodaMikeMapbox) [reply MapboxVisionTests/Mocks/FakeVideoSource.swift]: done

File: MapboxVisionTests/Mocks/FakeVideoSource.swift [hunk 17]
```diff
@@ -0,0 +1,105 @@
...
+        timer.suspend()
+    }
+
+    @objc
+    func videoSource() {
+        var buffer: CMSampleBuffer?
+
+        let pixelBuffer = makePixelBuffer()!
+        let duration = CMTime(value: 1, timescale: Constants.fps)
+        let pts = CMTime(value: framesAlreadyWritten, timescale: Constants.fps)
```
[the remark this answers is not in the document]
Comment (IodaMikeMapbox) [reply MapboxVisionTests/Mocks/FakeVideoSource.swift]: done

File: MapboxVisionTests/Mocks/FakeVideoSource.swift [hunk 18]
```diff
@@ -0,0 +1,105 @@
...
+
+    func start() {
+        timer.resume()
+    }
+
+    func stop() {
+        timer.suspend()
+    }
+
+    @objc
```
[the remark this answers is not in the document]
Comment (IodaMikeMapbox) [reply MapboxVisionTests/Mocks/FakeVideoSource.swift]: removed

File: MapboxVisionTests/Mocks/FakeVideoSource.swift (hunk 14 above)
[the remark this answers is not in the document]
Comment (IodaMikeMapbox) [reply MapboxVisionTests/Mocks/FakeVideoSource.swift]: done

File: MapboxVisionTests/Mocks/FakeVideoSource.swift (hunk 4 above)
Comment (IodaMikeMapbox) [reply MapboxVisionTests/Mocks/FakeVideoSource.swift]: removed

File: MapboxVisionTests/RecordCoordinatorTests.swift (hunk 5 above)
Comment (IodaMikeMapbox) [reply MapboxVisionTests/RecordCoordinatorTests.swift]: It's a helper method, the test in which we interested is using it

File: MapboxVisionTests/RecordCoordinatorTests.swift (hunk 6 above)
Comment (IodaMikeMapbox) [reply MapboxVisionTests/RecordCoordinatorTests.swift]: done

File: MapboxVisionTests/RecordCoordinatorTests.swift (hunk 7 above)
Comment (IodaMikeMapbox) [reply MapboxVisionTests/RecordCoordinatorTests.swift]: done

File: MapboxVisionTests/RecordCoordinatorTests.swift (hunk 8 above)
Comment (IodaMikeMapbox) [reply MapboxVisionTests/RecordCoordinatorTests.swift]: fixed

File: MapboxVisionTests/RecordCoordinatorTests.swift (hunk 9 above)
Comment (IodaMikeMapbox) [reply MapboxVisionTests/RecordCoordinatorTests.swift]: removed

File: MapboxVisionTests/RecordCoordinatorTests.swift (hunk 10 above)
Comment (IodaMikeMapbox) [reply MapboxVisionTests/RecordCoordinatorTests.swift]: changed

File: MapboxVisionTests/RecordCoordinatorTests.swift (hunk 11 above)
Comment (IodaMikeMapbox) [reply MapboxVisionTests/RecordCoordinatorTests.swift]: changed

File: MapboxVisionTests/RecordCoordinatorTests.swift (hunk 12 above)
Comment (IodaMikeMapbox) [reply MapboxVisionTests/RecordCoordinatorTests.swift]: done

File: MapboxVisionTests/RecordCoordinatorTests.swift [hunk 19]
```diff
@@ -72,6 +70,69 @@ final class RecordCoordinatorTests: XCTestCase {
...
+        videoSource.add(observer: coordinator)
+        videoSource.start()
+        coordinator.startRecording(referenceTime: 0, videoSettings: videoSettings) {}
+        _ = Timer.scheduledTimer(withTimeInterval: 4.0, repeats: false) { _ in
+            print("Make \(requests.count) clip\(requests.count == 1 ? "" : "s")")
+            requests.forEach {
+                self.coordinator.makeClip(from: $0.start, to: $0.end)
+            }
+
+            _ = Timer.scheduledTimer(withTimeInterval: 1.0, repeats: false) { _ in
```
[the remark this answers is not in the document]
Comment (IodaMikeMapbox) [reply MapboxVisionTests/RecordCoordinatorTests.swift]: changed

File: MapboxVisionTests/RecordCoordinatorTests.swift [hunk 20]
```diff
@@ -72,6 +70,69 @@ final class RecordCoordinatorTests: XCTestCase {
...
+                self.coordinator.stopRecording()
+
+                _ = Timer.scheduledTimer(withTimeInterval: 1.0, repeats: false) { _ in
```
[the remark this answers is not in the document]
Comment (IodaMikeMapbox) [reply MapboxVisionTests/RecordCoordinatorTests.swift]: done

File: MapboxVision/Services/Recording/RecordCoordinator.swift (hunk 3 above)
Comment (chezzdev) [reply MapboxVision/Services/Recording/RecordCoordinator.swift]: Have you got a chance to ensure it's working properly?

File: MapboxVisionTests/Mocks/MockVideoSource.swift [hunk 21]
```diff
@@ -1,10 +1,93 @@
...
+            observer.videoSource(self, didOutput: sample)
+        }
+    }
+
+    func makePixelBuffer() -> CVPixelBuffer? {
+        let attrs = [
+            kCVPixelBufferCGImageCompatibilityKey: kCFBooleanTrue,
+            kCVPixelBufferCGBitmapContextCompatibilityKey: kCFBooleanTrue,
+            kCVPixelBufferOpenGLESCompatibilityKey: kCFBooleanTrue,
+            kCVPixelBufferOpenGLESTextureCacheCompatibilityKey: kCFBooleanTrue,
```
Comment (chezzdev) [inline MapboxVisionTests/Mocks/MockVideoSource.swift]: It doesn't seem like we need those keys.

File: MapboxVisionTests/Mocks/MockVideoSource.swift [hunk 22]
```diff
@@ -1,10 +1,93 @@
...
+        let status = CVPixelBufferCreate(kCFAllocatorDefault, Int(Constants.frameWidth), Int(Constants.frameWidth), kCVPixelFormatType_32BGRA, attrs, &pixelBuffer)
+        guard status == kCVReturnSuccess else {
+            return nil
+        }
+
+        CVPixelBufferLockBaseAddress(pixelBuffer!, CVPixelBufferLockFlags(rawValue: 0))
+        let pixelData = CVPixelBufferGetBaseAddress(pixelBuffer!)
+
+        let rgbColorSpace = CGColorSpaceCreateDeviceRGB()
+        let context = CGContext(data: pixelData, width: Constants.frameWidth, height: Constants.frameHeight, bitsPerComponent: Constants.bitsInByte, bytesPerRow: CVPixelBufferGetBytesPerRow(pixelBuffer!), space: rgbColorSpace, bitmapInfo: CGImageAlphaInfo.noneSkipFirst.rawValue)
```
Comment (chezzdev) [inline MapboxVisionTests/Mocks/MockVideoSource.swift]: Please break this line into several ones and avoid force-unwraps.

File: MapboxVisionTests/Mocks/MockVideoSource.swift [hunk 23]
```diff
@@ -1,10 +1,93 @@
...
+        let color = UIColor(red: value, green: value, blue: value, alpha: value)
+        context!.setFillColor(color.cgColor)
+        context!.fill(CGRect(x: 0, y: 0, width: Constants.frameWidth, height: Constants.frameHeight))
+        UIGraphicsPopContext()
+        CVPixelBufferUnlockBaseAddress(pixelBuffer!, CVPixelBufferLockFlags(rawValue: 0))
 
-    func remove(observer: VideoSourceObserver) {}
+        return pixelBuffer
+    }
+    func make(from pixelBuffer: CVPixelBuffer) -> CMFormatDescription? {
```
Comment (chezzdev) [inline MapboxVisionTests/Mocks/MockVideoSource.swift]:
```suggestion
    private func makeFormatDescription(from pixelBuffer: CVPixelBuffer) -> CMFormatDescription? {
```

File: MapboxVisionTests/RecordCoordinatorTests.swift [hunk 24]
```diff
@@ -72,6 +70,83 @@ final class RecordCoordinatorTests: XCTestCase {
...
+
+        func recordingStarted(path: String) {
+        }
+
+        func recordingStopped(recordingPath: RecordingPath) {
+            onRecordingStopped()
+        }
+    }
+
+    private func performVideoClipping(with requests: [TestClipRequest], _ message: String = "", line: UInt = #line) {
```
Comment (chezzdev) [inline MapboxVisionTests/RecordCoordinatorTests.swift]: Could you please answer the previous comment:
> Also what's the point in line argument? Don't we want to know where exactly assert failed instead of where this function was called?

File: MapboxVisionTests/RecordCoordinatorTests.swift [hunk 25]
```diff
@@ -72,6 +70,83 @@ final class RecordCoordinatorTests: XCTestCase {
...
+
+        init(onRecordingStopped: @escaping () -> Void) {
+            self.onRecordingStopped = onRecordingStopped
+        }
+
+        func recordingStarted(path: String) {
+        }
+
+        func recordingStopped(recordingPath: RecordingPath) {
+            onRecordingStopped()
```
Comment (chezzdev) [inline MapboxVisionTests/RecordCoordinatorTests.swift]: `recordingStopped` method supplies a recording path that may be used for checking the correctness of its contents. Please use it instead of checking `DocumentsLocation.currentRecording.path`.

File: MapboxVisionTests/RecordCoordinatorTests.swift [hunk 26]
```diff
@@ -72,6 +70,83 @@ final class RecordCoordinatorTests: XCTestCase {
...
+        let expectation = XCTestExpectation(description: "All the requested clips are successfully cut")
+        let videoSource = MockVideoSource()
+        videoSource.add(observer: coordinator)
+        videoSource.start()
+
+        let recordDelegate = RecordDelegate {
+            let path = DocumentsLocation.currentRecording.path
+            let directoryContent = try? FileManager.default.contentsOfDirectory(at: URL(string: path)!, includingPropertiesForKeys: nil, options: [])
+
+            if let directoryContent = directoryContent {
```
Comment (chezzdev) [inline MapboxVisionTests/RecordCoordinatorTests.swift]: `guard` may help to make code more linear. WDYT?

File: MapboxVisionTests/RecordCoordinatorTests.swift [hunk 27]
```diff
@@ -72,6 +70,83 @@ final class RecordCoordinatorTests: XCTestCase {
...
+                for file in directoryContent where file.hasDirectoryPath {
+                    let subDirectoryContent = (try? FileManager.default.contentsOfDirectory(at: file, includingPropertiesForKeys: nil, options: []))
```
Comment (chezzdev) [inline MapboxVisionTests/RecordCoordinatorTests.swift]: No need for the braces.

File: MapboxVisionTests/RecordCoordinatorTests.swift [hunk 28]
```diff
@@ -72,6 +70,83 @@ final class RecordCoordinatorTests: XCTestCase {
...
+
+                    if let subDirectoryContent = subDirectoryContent {
```
Comment (chezzdev) [inline MapboxVisionTests/RecordCoordinatorTests.swift]: Some note about `guard`.

File: MapboxVisionTests/RecordCoordinatorTests.swift [hunk 29]
```diff
@@ -72,6 +70,83 @@ final class RecordCoordinatorTests: XCTestCase {
...
+
+            DispatchQueue.main.asyncAfter(deadline: .now() + 1.0) { [unowned self] in
+                self.coordinator.stopRecording()
+            }
+        }
+
+        XCTWaiter().wait(for: [expectation], timeout: 10.0)
+    }
+
+    func testVideoClipping() {
```
Comment (chezzdev) [inline MapboxVisionTests/RecordCoordinatorTests.swift]: Could you please organize test-cases together and private helper functions separately (later in the file)?

File: MapboxVisionTests/Mocks/MockVideoSource.swift (hunk 21 above)
Comment (IodaMikeMapbox) [reply MapboxVisionTests/Mocks/MockVideoSource.swift]: removed all but metal compatibility in order to have an ability to use the class with our renderer

File: MapboxVisionTests/RecordCoordinatorTests.swift (hunk 25 above)
Comment (IodaMikeMapbox) [reply MapboxVisionTests/RecordCoordinatorTests.swift]: done

File: MapboxVisionTests/RecordCoordinatorTests.swift (hunk 26 above)
Comment (IodaMikeMapbox) [reply MapboxVisionTests/RecordCoordinatorTests.swift]: I want to have one point of expectation fulfill

File: MapboxVisionTests/RecordCoordinatorTests.swift (hunk 27 above)
Comment (IodaMikeMapbox) [reply MapboxVisionTests/RecordCoordinatorTests.swift]: right, removed

File: MapboxVisionTests/RecordCoordinatorTests.swift (hunk 28 above)
Comment (IodaMikeMapbox) [reply MapboxVisionTests/RecordCoordinatorTests.swift]: same answer about `guard`

File: MapboxVisionTests/RecordCoordinatorTests.swift (hunk 29 above)
Comment (IodaMikeMapbox) [reply MapboxVisionTests/RecordCoordinatorTests.swift]: moved to the end of the class

File: MapboxVisionTests/RecordCoordinatorTests.swift (hunk 24 above)
Comment (IodaMikeMapbox) [reply MapboxVisionTests/RecordCoordinatorTests.swift]: > It's a helper method, the test in which we interested uses it
We want to know that the test failed, not its underlying implementation

File: MapboxVision/Services/Recording/RecordCoordinator.swift (hunk 3 above)
Comment (IodaMikeMapbox) [reply MapboxVision/Services/Recording/RecordCoordinator.swift]: yes, works as expected

File: MapboxVisionTests/Mocks/MockVideoSource.swift (hunk 23 above)
Comment (chezzdev) [reply MapboxVisionTests/Mocks/MockVideoSource.swift]: This was not resolved.

File: MapboxVisionTests/RecordCoordinatorTests.swift (hunk 24 above)
Comment (chezzdev) [reply MapboxVisionTests/RecordCoordinatorTests.swift]: I think this implementation is a part of the test and it's interesting which particular assert has failed. But it's up to you.

File: MapboxVisionTests/RecordCoordinatorTests.swift [hunk 30]
```diff
@@ -86,6 +148,71 @@ final class RecordCoordinatorTests: XCTestCase {
...
+            requests.forEach {
+                self.coordinator.makeClip(from: $0.start, to: $0.end)
+            }
+
+            DispatchQueue.main.asyncAfter(deadline: .now() + 1.0) { [unowned self] in
+                self.coordinator.stopRecording()
+            }
+        }
+
+        XCTWaiter().wait(for: [expectation], timeout: 10.0)
```
[the remark this answers is not in the document]
Comment (IodaMikeMapbox) [reply MapboxVisionTests/RecordCoordinatorTests.swift]: done

File: MapboxVisionTests/Mocks/MockVideoSource.swift [hunk 31]
```diff
@@ -1,10 +1,97 @@
...
+        let color = UIColor(red: value, green: value, blue: value, alpha: value)
+        context!.setFillColor(color.cgColor)
+        context!.fill(CGRect(x: 0, y: 0, width: Constants.frameWidth, height: Constants.frameHeight))
+        UIGraphicsPopContext()
+        CVPixelBufferUnlockBaseAddress(pixelBuffer, CVPixelBufferLockFlags(rawValue: 0))
 
-    func remove(observer: VideoSourceObserver) {}
+        return pixelBuffer
+    }
+    func makeFormatDescription(from pixelBuffer: CVPixelBuffer) -> CMFormatDescription? {
```
[the remark this answers is not in the document]
Comment (IodaMikeMapbox) [reply MapboxVisionTests/Mocks/MockVideoSource.swift]: done

File: MapboxVisionTests/RecordCoordinatorTests.swift [hunk 32]
```diff
@@ -72,6 +70,70 @@ final class RecordCoordinatorTests: XCTestCase {
...
+            startSavingSession: { _ in },
+            stopSavingSession: { }
+        ))
+
+        var didCreateExternalFolder = false
+        let testFolderPath = DocumentsLocation.cache.path.appendingPathComponent("test", isDirectory: true)
+
+        let recordDelegate = RecordDelegate()
+        recordDelegate.onRecordingStopped = { recordingPath in
+            if recordingPath.recordingPath.lastPathComponent == testFolderPath.lastPathComponent {
```
[the remark this answers is not in the document]
Comment (IodaMikeMapbox) [reply MapboxVisionTests/RecordCoordinatorTests.swift]: yes, but the recorder adds extra `/` to the path which complicates comparison, meanwhile `lastPathComponent` comparison is good enough for the current purpose

[the remark this answers is not in the document]
Comment (chezzdev) [reply MapboxVisionTests/RecordCoordinatorTests.swift]: As discussed `resolvingSymlinksInPath` can be used for comparison.

[the remark this answers is not in the document]
Comment (IodaMikeMapbox) [reply MapboxVisionTests/RecordCoordinatorTests.swift]: done

File: MapboxVisionTests/Mocks/MockVideoSource.swift [hunk 33]
```diff
@@ -1,10 +1,101 @@
...
+    private let processingQueue = DispatchQueue(label: "com.mapbox.RecordCoordinatorTest.VideoSource")
+    private lazy var timer: DispatchSourceTimer = {
+        let timer = DispatchSource.makeTimerSource()
+        timer.schedule(deadline: .now() + Constants.frameDelay, repeating: Constants.frameDelay)
+        timer.setEventHandler { [weak self] in
+            self?.emitNewBuffer()
+        }
+        return timer
+    }()
+    private var framesAlreadyWritten: Int64 = 0
```
Comment (dersim-davaod) [inline MapboxVisionTests/Mocks/MockVideoSource.swift]:
```suggestion
    private var framesAlreadyWritten: UInt64 = 0
```

File: MapboxVisionTests/Mocks/MockVideoSource.swift [hunk 34]
```diff
@@ -1,10 +1,101 @@
...
+    }
+
+    private func makePixelBuffer() -> CVPixelBuffer? {
+        let attrs = [
+            kCVPixelBufferMetalCompatibilityKey: kCFBooleanTrue
+        ] as CFDictionary
+        var pixelBufferUnwrapped: CVPixelBuffer?
+        let status = CVPixelBufferCreate(kCFAllocatorDefault, Int(Constants.frameWidth), Int(Constants.frameWidth), kCVPixelFormatType_32BGRA, attrs, &pixelBufferUnwrapped)
+        guard status == kCVReturnSuccess, let pixelBuffer = pixelBufferUnwrapped else {
+            return nil
```
Comment (dersim-davaod) [inline MapboxVisionTests/Mocks/MockVideoSource.swift]: Can we have a situation where `status != kCVReturnSuccess` AND `pixelBuffer != nil`?
Should we perform releasing for memory then?

File: MapboxVisionTests/Mocks/MockVideoSource.swift [hunk 35]
```diff
@@ -1,10 +1,101 @@
...
+        CVPixelBufferUnlockBaseAddress(pixelBuffer, CVPixelBufferLockFlags(rawValue: 0))
 
-    func add(observer: VideoSourceObserver) {}
+        return pixelBuffer
+    }
 
-    func remove(observer: VideoSourceObserver) {}
+    private func makeFormatDescription(from pixelBuffer: CVPixelBuffer) -> CMFormatDescription? {
+        var formatDescription: CMFormatDescription?
+        CMVideoFormatDescriptionCreateForImageBuffer(allocator: kCFAllocatorDefault, imageBuffer: pixelBuffer, formatDescriptionOut: &formatDescription)
```
Comment (dersim-davaod) [inline MapboxVisionTests/Mocks/MockVideoSource.swift]: Should we check return value?

File: MapboxVisionTests/RecordCoordinatorTests.swift [hunk 36]
```diff
@@ -72,6 +70,70 @@ final class RecordCoordinatorTests: XCTestCase {
...
+            TestClipRequest(start: 3.0, end: 4.0),
+            TestClipRequest(start: 3.0, end: 8.0)
+        ], "Failed to clip videos from a chunk")
+    }
+
+    func testSessionRestarting() {
+        let expectation = XCTestExpectation(description: "All the recording sessions are finished")
+
+        // Given
+        // SessionRecorder
```
Comment (dersim-davaod) [inline MapboxVisionTests/RecordCoordinatorTests.swift]: Redundant comment?

File: MapboxVisionTests/RecordCoordinatorTests.swift [hunk 37]
```diff
@@ -72,6 +70,70 @@ final class RecordCoordinatorTests: XCTestCase {
...
+                expectation.fulfill()
+            }
+        }
+        sessionRecorder.delegate = recordDelegate
+        let videoSource = MockVideoSource()
+        videoSource.add(observer: sessionRecorder)
+        videoSource.start()
+        sessionRecorder.start()
+
+        DispatchQueue.main.asyncAfter(deadline: .now() + 0.5) {
```
Comment (dersim-davaod) [inline MapboxVisionTests/RecordCoordinatorTests.swift]: Magic numbers? Could you please check here and below?

File: MapboxVisionTests/RecordCoordinatorTests.swift [hunk 38]
```diff
@@ -86,6 +148,71 @@ final class RecordCoordinatorTests: XCTestCase {
...
+                if let directoryContent = directoryContent {
+                    let numberOfVideos = directoryContent.filter {
+                        $0.pathExtension == path.settings.fileExtension
+                    }
+                    .count
+
+                    didCreateAllClips = numberOfVideos == requests.count
+                }
+            }
+            expectation.fulfill()
```
Comment (dersim-davaod) [inline MapboxVisionTests/RecordCoordinatorTests.swift]: Comment for `testVideoClipping` (line 79) say:
As a result we should get the same number of video files on filesystem
Should we then to fulfill the expectation only when `didCreateAllClips == true`?

```suggestion
    if didCreateAllClips {
            expectation.fulfill()
    }
```

WDYT?

File: MapboxVisionTests/RecordCoordinatorTests.swift [hunk 39]
```diff
@@ -86,6 +148,71 @@ final class RecordCoordinatorTests: XCTestCase {
...
+        }
+
+        coordinator.delegate = recordDelegate
+        coordinator.startRecording(referenceTime: 0, videoSettings: videoSettings) {}
+        DispatchQueue.main.asyncAfter(deadline: .now() + 4.0) { [unowned self] in
```
[the remark this answers is not in the document]
Comment (dersim-davaod) [reply MapboxVisionTests/RecordCoordinatorTests.swift]: Here and below

File: MapboxVisionTests/RecordCoordinatorTests.swift [hunk 40]
```diff
@@ -72,6 +70,70 @@ final class RecordCoordinatorTests: XCTestCase {
         XCTAssert(directoryExists(at: recordingPath), "Recording should be saved at \(recordingPath) after recording is stopped")
     }
 
+    func testVideoClipping() {
+        // Given
+        // a list of clip requests
+        // When
+        // we try to make clips with them
+        // Then
+        // we should get the same number of video files on filesystem
```
Comment (dersim-davaod) [inline MapboxVisionTests/RecordCoordinatorTests.swift]: Probably a bit confusing comment - could you please take a look at comment for `performVideoClipping` func?

File: MapboxVision/Services/Recording/RecordCoordinator.swift [hunk 41]
```diff
@@ -96,104 +101,130 @@ final class RecordCoordinator {
...
-            for chunk in (startChunk + 1)..<endChunk {
-                let clipStart = Float(chunk) * chunkLength
-                let clipEnd = Float(chunk + 1) * chunkLength
-                copyClip(chunk: chunk, clipStart: clipStart, clipEnd: clipEnd)
+    func saveImage(image: Image, path: String) {
+        processingQueue.async { [weak self] in
+            guard let self = self else { return }
+            guard let recordingPath = self.currentRecordingPath else { return }
+
+            guard let uiimage = image.getUIImage() else {
```
[the remark this answers is not in the document]
Comment (IodaMikeMapbox) [reply MapboxVision/Services/Recording/RecordCoordinator.swift]: will change

File: MapboxVisionTests/Mocks/MockVideoSource.swift (hunk 33 above)
Comment (IodaMikeMapbox) [reply MapboxVisionTests/Mocks/MockVideoSource.swift]: will change

File: MapboxVisionTests/Mocks/MockVideoSource.swift (hunk 34 above)
Comment (IodaMikeMapbox) [reply MapboxVisionTests/Mocks/MockVideoSource.swift]: it is possible, yes. Releasing what do you propose?

File: MapboxVisionTests/Mocks/MockVideoSource.swift (hunk 35 above)
Comment (IodaMikeMapbox) [reply MapboxVisionTests/Mocks/MockVideoSource.swift]: return value nullable, but the caller doesn't check for nil, will fix

File: MapboxVisionTests/Mocks/MockVideoSource.swift (hunk 34 above)
Comment (dersim-davaod) [reply MapboxVisionTests/Mocks/MockVideoSource.swift]: Oh, I'm sorry, ARC does the job. There's no need for additional operations.

File: MapboxVisionTests/RecordCoordinatorTests.swift (hunk 38 above)
Comment (IodaMikeMapbox) [reply MapboxVisionTests/RecordCoordinatorTests.swift]: the expectation doesn't match the test's goal, we can change the way we fulfill the expectation as you suggest but it doesn't make much sense for me

File: MapboxVision/Services/Recording/RecordCoordinator.swift (hunk 41 above)
[the remark this answers is not in the document]
Comment (IodaMikeMapbox) [reply MapboxVision/Services/Recording/RecordCoordinator.swift]: done

File: MapboxVisionTests/Mocks/MockVideoSource.swift (hunk 33 above)
Comment (IodaMikeMapbox) [reply MapboxVisionTests/Mocks/MockVideoSource.swift]: won't change, `CMTime` uses `Int64`

File: MapboxVisionTests/RecordCoordinatorTests.swift (hunk 39 above)
[the remark this answers is not in the document]
Comment (IodaMikeMapbox) [reply MapboxVisionTests/RecordCoordinatorTests.swift]: done

File: MapboxVisionTests/Mocks/MockVideoSource.swift (hunk 35 above)
Comment (IodaMikeMapbox) [reply MapboxVisionTests/Mocks/MockVideoSource.swift]: fixed

File: MapboxVisionTests/RecordCoordinatorTests.swift (hunk 36 above)
Comment (IodaMikeMapbox) [reply MapboxVisionTests/RecordCoordinatorTests.swift]: don't think so

File: MapboxVisionTests/RecordCoordinatorTests.swift (hunk 37 above)
Comment (IodaMikeMapbox) [reply MapboxVisionTests/RecordCoordinatorTests.swift]: done

File: MapboxVisionTests/RecordCoordinatorTests.swift (hunk 38 above)
Comment (IodaMikeMapbox) [reply MapboxVisionTests/RecordCoordinatorTests.swift]: after discussion decided that the expectation had incorrect description, fixed
