### PR TITLE
Fixed destructors without calling destroy

### LINKED ISSUE #130: Fix crashes caused by multiple calling of Destroy in deallocators
### Summary
I noticed that VisionExamples app crashes at runtime because of calling `VisionManager::Destroy` multiple times, I think we haven't faced with this bug because teaser app doesn't recreate instance of VisionManager multiple times.

### Steps to reproduce
1. Run the VisionExamples app;
2. Choose "Over speeding detection";
3. Tap back button.

### PR DESCRIPTION
**Pull request by IodaMikeMapbox**
The pr fixes logic of VisionManager's destructor for cases when destroy was/wasn't called.
For now we could call destroy method in VisionManager's destructor but we don't want to because of consistency over all our platforms.
There were added mocks of VisionManager's dependencies in order to write tests for destruction logic. While adding mocks the recording permission logic was edited that is why there were implement also tests for recording permissions.

Checks:

* [x] Update changelog
* [x] Rebase to `dev` branch
* [x] Assign reviewers

Linked issues:
Resolves #130

### CODE REVIEW

File: MapboxVisionTests/VisionManagerTests.swift [hunk 1]
```diff
@@ -0,0 +1,161 @@
...
+
+        XCTAssert(recorder.actionsLog.elementsEqual(expectedActions))
+
+        visionManager.stopRecording()
+        visionManager.stop()
+    }
+}
+
+private extension XCTestCase {
+    func expectAssertionFailure(testcase: @escaping () -> Void) {
```
Comment (chezzdev) [inline MapboxVisionTests/VisionManagerTests.swift]: WDYT about making the signature of this method as close to XCTest as possible (with message and stuff)? It also may be top-level function.

File: MapboxVisionTests/VisionManagerTests.swift [hunk 2]
```diff
@@ -0,0 +1,161 @@
...
+        // Nevertheless the logic was sort of right, it should do assertFailure on deinit without destroy was called
+        //
+        // Given
+        // object of VisionManager
+        // When
+        // we deallocate it without destroy
+        // Then
+        // Should be assertion failure
+        expectAssertionFailure { [weak self] in
+            self?.dependencies?.native.destroy()
```
Comment (chezzdev) [inline MapboxVisionTests/VisionManagerTests.swift]: It doesn't seem that this cleanup is needed.

File: MapboxVisionTests/VisionManagerTests.swift [hunk 3]
```diff
@@ -0,0 +1,161 @@
...
+            self?.visionManager = nil
+        }
+    }
+
+    func test_NoAssertOnVisionManagerDeallocAfterDestroy() {
+        // Given
+        // object of VisionManager
+        // When
+        // we deallocate it with destroy
```
Comment (chezzdev) [inline MapboxVisionTests/VisionManagerTests.swift]:
```suggestion
        // we call destroy and release the instance
```

File: MapboxVisionTests/VisionManagerTests.swift [hunk 4]
```diff
@@ -0,0 +1,161 @@
+@testable import MapboxVision
+import XCTest
+
+class VisionManagerTests: XCTestCase {
+    var visionManager: VisionManager?
```
Comment (chezzdev) [inline MapboxVisionTests/VisionManagerTests.swift]: I think it's safe to make it force-unwrapped to avoid unnecessary unwrapping.

File: MapboxVision/VisionManager/SessionRecorderProtocol.swift [hunk 5]
```diff
@@ -0,0 +1,15 @@
+import CoreMedia
+import Foundation
+
+protocol SessionRecorderProtocol: AnyObject {
+    func stop()
+    func startInternal()
+    func startExternal(withPath path: String)
```
[the remark this answers is not in the document]
Comment (IodaMikeMapbox) [reply MapboxVision/VisionManager/SessionRecorderProtocol.swift]: After discussion with @chezzdev decided that the original solution is better fits here because it conforms [Swift API design guidlines](https://swift.org/documentation/api-design-guidelines/), so the suggestion is declined

File: MapboxVision/Helpers/AssertionFailure.swift [hunk 6]
```diff
@@ -0,0 +1,23 @@
+import Foundation
+
+func assertionFailure(_ message: @autoclosure () -> String = String(), file: StaticString = #file, line: UInt = #line) {
+    AssertFailureUtil.assertFailure(message(), file, line)
+}
+
+enum AssertFailureUtil {
+    // 1
```
[the remark this answers is not in the document]
Comment (IodaMikeMapbox) [reply MapboxVision/Helpers/AssertionFailure.swift]: Agree, will add description

File: MapboxVision/VisionManager/VisionManager.swift [hunk 7]
```diff
@@ -227,16 +231,16 @@ public final class VisionManager: BaseVisionManager {
         resume()
     }
 
-    private func tryRecording(mode: SessionRecorder.Mode) {
-        guard mode.isExternal || currentCountry.allowsRecording else { return }
-        dependencies.recorder.start(mode: mode)
+    private func tryRecording() {
```
[the remark this answers is not in the document]
Comment (IodaMikeMapbox) [reply MapboxVision/VisionManager/VisionManager.swift]: Makes sense, will do

File: MapboxVision/VisionManager/VisionManagerNativeProtocol.swift [hunk 8]
```diff
@@ -0,0 +1,30 @@
+import Foundation
+import MapboxVisionNative
+
+protocol VisionManagerBaseNativeProtocol: AnyObject {
+    var config: CoreConfig { get set }
+
+    func pixel(toWorld screenCoordinate: Point2D) -> WorldCoordinate?
+    func world(toPixel worldCoordinate: WorldCoordinate) -> Point2D?
+    func geo(toWorld geoCoordinate: GeoCoordinate) -> WorldCoordinate
```
[the remark this answers is not in the document]
Comment (IodaMikeMapbox) [reply MapboxVision/VisionManager/VisionManagerNativeProtocol.swift]: You are right, will fix

File: MapboxVisionTests/VisionManagerTests.swift [hunk 9]
```diff
@@ -0,0 +1,161 @@
...
+    var fatalErrorMessage: String?
```
[the remark this answers is not in the document]
Comment (IodaMikeMapbox) [reply MapboxVisionTests/VisionManagerTests.swift]: agree, will remove

File: MapboxVisionTests/VisionManagerTests.swift (hunk 2 above)
Comment (IodaMikeMapbox) [reply MapboxVisionTests/VisionManagerTests.swift]: Yeah, since it's a mocked native, will remove

File: MapboxVisionTests/VisionManagerTests.swift (hunk 3 above)
Comment (IodaMikeMapbox) [reply MapboxVisionTests/VisionManagerTests.swift]: will change

File: MapboxVisionTests/VisionManagerTests.swift (hunk 1 above)
Comment (IodaMikeMapbox) [reply MapboxVisionTests/VisionManagerTests.swift]: done

File: MapboxVisionTests/VisionManagerTests.swift [hunk 10]
```diff
@@ -0,0 +1,161 @@
...
+    var dependencies: VisionDependencies?
```
[the remark this answers is not in the document]
Comment (IodaMikeMapbox) [reply MapboxVisionTests/VisionManagerTests.swift]: I prefer to use soft unwrappings

File: MapboxVisionTests/VisionManagerTests.swift (hunk 4 above)
Comment (IodaMikeMapbox) [reply MapboxVisionTests/VisionManagerTests.swift]: I prefer to use soft unwrappings

File: MapboxVisionTests/VisionManagerTests.swift [hunk 11]
```diff
@@ -0,0 +1,139 @@
...
+        visionManager.onCountryUpdated(.china)
+        visionManager.onCountryUpdated(.other)
+        visionManager.onCountryUpdated(.unknown)
+
+        // Then
+        // we expect that visionManager will call SessionRecorder's method `startInternal` for all countries but China and that there
+        // will no be any other calls to SessionRecorder. For China we expect `stop` method to be called
+
+        let expectedActions: [MockSessionRecorder.Action] = [
+            .startInternal, // USA
```
Comment (dersim-davaod) [inline MapboxVisionTests/VisionManagerTests.swift]: Instead of adding comments (`// USA`, `// UK` etc.) probably it would be better to introduce a typed dictionary similar to [country : expectedActionForCountry].
Then you can setup countries in for-case loop and check elements from actionsLog.

WDYT? Does that make sense?

File: MapboxVisionTests/VisionManagerTests.swift [hunk 12]
```diff
@@ -0,0 +1,139 @@
...
+            "VisionManager should be successfully deallocated after calling destroy and releasing the object"
+        )
+    }
+
+    func test_RecordingPermissions() {
+        // Given
+        // VisionManager with default country
+
+        guard let visionManager = self.visionManager, let recorder = dependencies?.recorder as? MockSessionRecorder else {
+            XCTAssert(false)
```
Comment (dersim-davaod) [inline MapboxVisionTests/VisionManagerTests.swift]: Please use XCTFail and include description in assert.

File: MapboxVisionTests/VisionManagerTests.swift [hunk 13]
```diff
@@ -0,0 +1,139 @@
...
+import XCTest
+
+class VisionManagerTests: XCTestCase {
+    var visionManager: VisionManager?
+    var dependencies: VisionDependencies?
+
+    override func setUp() {
+        super.setUp()
+
+        let native = MockNative()
```
Comment (dersim-davaod) [inline MapboxVisionTests/VisionManagerTests.swift]: Can we pass `MockNative()` into `dependencies` without creating a separate constant (like everything else - `MockSynchronizable()` etc.)?

File: MapboxVisionTests/VisionManagerTests.swift [hunk 14]
```diff
@@ -0,0 +1,139 @@
...
+
+        visionManager.onCountryUpdated(.USA)
+        visionManager.onCountryUpdated(.UK)
+        visionManager.onCountryUpdated(.china)
+        visionManager.onCountryUpdated(.other)
+        visionManager.onCountryUpdated(.unknown)
+
+        // Then
+        // we expect that visionManager will call SessionRecorder's method `startInternal` for all countries but China and that there
+        // will no be any other calls to SessionRecorder. For China we expect `stop` method to be called
```
Comment (dersim-davaod) [inline MapboxVisionTests/VisionManagerTests.swift]: nit:

As far as I understand from comment we're trying to test 2 cases here:
- we have expected actions for each case;
- amount of final actions exactly equal to amount of expected actions);

If so probably we can add additional XCTAssert below. One for the first case and another one for the second.

File: MapboxVisionTests/VisionManagerTests.swift (hunk 13 above)
Comment (IodaMikeMapbox) [reply MapboxVisionTests/VisionManagerTests.swift]: yes, fixed

File: MapboxVisionTests/VisionManagerTests.swift (hunk 12 above)
Comment (IodaMikeMapbox) [reply MapboxVisionTests/VisionManagerTests.swift]: done

File: MapboxVisionTests/Mocks/MockSessionRecorder.swift [hunk 15]
```diff
@@ -0,0 +1,41 @@
...
+
+class MockSessionRecorder: SessionRecorderProtocol {
+    enum Action: Equatable {
+        case stop
+        case startInternal
+        case startExternal(withPath: String)
+        case handleFrame(frame: CMSampleBuffer)
+    }
+
+    var actionsLog: [Action] = []
```
[the remark this answers is not in the document]
Comment (IodaMikeMapbox) [reply MapboxVisionTests/Mocks/MockSessionRecorder.swift]: agree

File: MapboxVisionTests/VisionManagerTests.swift [hunk 16]
```diff
@@ -0,0 +1,139 @@
...
+        )
+    }
+
+    func test_NoAssertOnVisionManagerDeallocAfterDestroy() {
+        // Given
+        // object of VisionManager
+
+        // When
+        // we call destroy and release the instance
+        self.visionManager?.destroy()
```
[the remark this answers is not in the document]
Comment (IodaMikeMapbox) [reply MapboxVisionTests/VisionManagerTests.swift]: fine

File: MapboxVisionTests/VisionManagerTests.swift [hunk 17]
```diff
@@ -0,0 +1,139 @@
...
+        // Description:
+        // We called destroy in destructors of VisionManager, BaseVisionManager, VisionManagerNative and VisionManagerBaseNative,
+        // so VisionManagerBaseNative's destroy method called multiple times, so we tried to destroy already destroyed resources,
+        // which caused an EXC_BAD_ACCESS.
+        //
+        // Nevertheless the logic was sort of right, it should do assertFailure on deinit without destroy was called
+        //
+        // Given
+        // object of VisionManager
+        // When
```
[the remark this answers is not in the document]
Comment (IodaMikeMapbox) [reply MapboxVisionTests/VisionManagerTests.swift]: ok

File: MapboxVisionTests/VisionManagerTests.swift [hunk 18]
```diff
@@ -0,0 +1,139 @@
...
+    }
+
+    func test_AssertOnVisionManagerDeallocWithoutDestroy() {
+        // Description:
+        // We called destroy in destructors of VisionManager, BaseVisionManager, VisionManagerNative and VisionManagerBaseNative,
+        // so VisionManagerBaseNative's destroy method called multiple times, so we tried to destroy already destroyed resources,
+        // which caused an EXC_BAD_ACCESS.
+        //
+        // Nevertheless the logic was sort of right, it should do assertFailure on deinit without destroy was called
+        //
```
[the remark this answers is not in the document]
Comment (IodaMikeMapbox) [reply MapboxVisionTests/VisionManagerTests.swift]: ok

File: MapboxVisionTests/VisionManagerTests.swift [hunk 19]
```diff
@@ -0,0 +1,139 @@
...
+            recorder: MockSessionRecorder(),
+            dataProvider: MockDataProvider(),
+            deviceInfo: DeviceInfoProvider()
+        )
+
+        self.visionManager = VisionManager(dependencies: dependencies!, videoSource: MockVideoSource())
+    }
+
+    func test_AssertOnVisionManagerDeallocWithoutDestroy() {
+        // Description:
```
[the remark this answers is not in the document]
Comment (IodaMikeMapbox) [reply MapboxVisionTests/VisionManagerTests.swift]: ok

File: MapboxVisionTests/VisionManagerTests.swift [hunk 20]
```diff
@@ -0,0 +1,139 @@
...
+        visionManager.onCountryUpdated(.USA)
+        visionManager.onCountryUpdated(.UK)
+        visionManager.onCountryUpdated(.china)
+        visionManager.onCountryUpdated(.other)
+        visionManager.onCountryUpdated(.unknown)
+
+        // Then
+        // we expect that visionManager will call SessionRecorder's method `startInternal` for all countries but China and that there
+        // will no be any other calls to SessionRecorder. For China we expect `stop` method to be called
+
```
[the remark this answers is not in the document]
Comment (IodaMikeMapbox) [reply MapboxVisionTests/VisionManagerTests.swift]: ok

File: MapboxVisionTests/AssertAssertionFailure.swift [hunk 21]
```diff
@@ -0,0 +1,30 @@
+@testable import MapboxVision
+import XCTest
+
+func MVTAssertAssertionFailure<T>(_ testcase: @autoclosure () -> T, _ message: @autoclosure () -> String = "", file: StaticString = #file, line: UInt = #line) {
+    var assertionFailureAccured = false
+
+    AssertFailureUtil.replaceFatalError { _, _, _ in
```
[the remark this answers is not in the document]
Comment (IodaMikeMapbox) [reply MapboxVisionTests/AssertAssertionFailure.swift]: fixed

File: MapboxVisionTests/AssertAssertionFailure.swift [hunk 22]
```diff
@@ -0,0 +1,30 @@
+@testable import MapboxVision
+import XCTest
+
+func MVTAssertAssertionFailure<T>(_ testcase: @autoclosure () -> T, _ message: @autoclosure () -> String = "", file: StaticString = #file, line: UInt = #line) {
+    var assertionFailureAccured = false
```
[the remark this answers is not in the document]
Comment (IodaMikeMapbox) [reply MapboxVisionTests/AssertAssertionFailure.swift]: fixed

File: MapboxVisionTests/VisionManagerTests.swift [hunk 23]
```diff
@@ -0,0 +1,139 @@
...
+            synchronizer: MockSynchronizable(),
+            recorder: MockSessionRecorder(),
+            dataProvider: MockDataProvider(),
+            deviceInfo: DeviceInfoProvider()
+        )
+
+        self.visionManager = VisionManager(dependencies: dependencies!, videoSource: MockVideoSource())
+    }
+
+    func test_AssertOnVisionManagerDeallocWithoutDestroy() {
```
[the remark this answers is not in the document]
Comment (IodaMikeMapbox) [reply MapboxVisionTests/VisionManagerTests.swift]: ok

File: MapboxVisionTests/AssertAssertionFailure.swift [hunk 24]
```diff
@@ -0,0 +1,30 @@
+@testable import MapboxVision
+import XCTest
+
+func MVTAssertAssertionFailure<T>(_ testcase: @autoclosure () -> T, _ message: @autoclosure () -> String = "", file: StaticString = #file, line: UInt = #line) {
```
[the remark this answers is not in the document]
Comment (IodaMikeMapbox) [reply MapboxVisionTests/AssertAssertionFailure.swift]: to clarify that it's a custom assert, but it can be omitted

File: MapboxVision/Helpers/AssertionFailure.swift [hunk 25]
```diff
@@ -0,0 +1,42 @@
...
+
+    /**
+     The method allows us to mock the behavior of `assertionFailure` in order to catch its calling without terminating execution of a test.
+     */
+    static func replaceFatalError(closure: @escaping (String, StaticString, UInt) -> Void) {
+        assertFailure = closure
+    }
+
+    /**
+     Restores default value of `assertFailure`
```
[the remark this answers is not in the document]
Comment (IodaMikeMapbox) [reply MapboxVision/Helpers/AssertionFailure.swift]: fixed

File: MapboxVision/Helpers/AssertionFailure.swift [hunk 26]
```diff
@@ -0,0 +1,42 @@
+import Foundation
+
+/**
+ We have speciphied logic of some compenents which includes calling of `assertionFailure` in debug envirnment in some circumstances,
+ e.g. `VisionManager` should call `assertFailure` when we forgot to call method `destroy` before releasing instance of the object.
```
[the remark this answers is not in the document]
Comment (IodaMikeMapbox) [reply MapboxVision/Helpers/AssertionFailure.swift]: right, of the class

File: MapboxVision/Helpers/AssertionFailure.swift [hunk 27]
```diff
@@ -0,0 +1,42 @@
+import Foundation
+
+/**
+ We have speciphied logic of some compenents which includes calling of `assertionFailure` in debug envirnment in some circumstances,
```
[the remark this answers is not in the document]
Comment (IodaMikeMapbox) [reply MapboxVision/Helpers/AssertionFailure.swift]: fixed

File: MapboxVision/Helpers/AssertionFailure.swift [hunk 28]
```diff
@@ -0,0 +1,42 @@
...
+ e.g. `VisionManager` should call `assertFailure` when we forgot to call method `destroy` before releasing instance of the object.
+
+ We want to have a test for that kind of logic because it's too easy to conclude that the `VisionManager` should behave in another
+ way. Actually we had incorrect logic while ago with that part and it was a bug.
+ In order to test calling of `assertionFailure` we should override this method and add an ability to mock the implementation and add
+ our checks
+ */
+
```
[the remark this answers is not in the document]
Comment (IodaMikeMapbox) [reply MapboxVision/Helpers/AssertionFailure.swift]: fixed

File: MapboxVisionTests/Mocks/MockPlatform.swift [hunk 29]
```diff
@@ -0,0 +1,12 @@
+@testable import MapboxVision
+
+class MockPlatform: NSObject, PlatformInterface {
+    func makeVideoClip(_ startTime: Float, end endTime: Float) {
```
[the remark this answers is not in the document]
Comment (IodaMikeMapbox) [reply MapboxVisionTests/Mocks/MockPlatform.swift]: done

File: MapboxVisionTests/Mocks/MockNative.swift [hunk 30]
```diff
@@ -0,0 +1,45 @@
...
+@testable import MapboxVisionNative
+
+class MockNative: VisionManagerNativeProtocol {
+    var config = CoreConfig()
+
+    var sensors: SensorsInterface {
+        return MockSensors()
+    }
+
+    func start(_: VisionDelegate) {
```
[the remark this answers is not in the document]
Comment (IodaMikeMapbox) [reply MapboxVisionTests/Mocks/MockNative.swift]: done

File: MapboxVisionARTests/MapboxVisionARTests.swift [hunk 31]
```diff
@@ -0,0 +1,27 @@
+//
+
+import XCTest
+
+class MapboxVisionARTests: XCTestCase {
+
+    override func setUp() {
```
[the remark this answers is not in the document]
Comment (IodaMikeMapbox) [reply MapboxVisionARTests/MapboxVisionARTests.swift]: removed

File: MapboxVisionARTests/MapboxVisionARTests.swift [hunk 32]
```diff
@@ -0,0 +1,27 @@
+//
```
[the remark this answers is not in the document]
Comment (IodaMikeMapbox) [reply MapboxVisionARTests/MapboxVisionARTests.swift]: removed entire file

File: MapboxVision/Helpers/AssertionFailure.swift [hunk 33]
```diff
@@ -0,0 +1,42 @@
+import Foundation
+
+/**
+ We have speciphied logic of some compenents which includes calling of `assertionFailure` in debug envirnment in some circumstances,
+ e.g. `VisionManager` should call `assertFailure` when we forgot to call method `destroy` before releasing instance of the object.
+
+ We want to have a test for that kind of logic because it's too easy to conclude that the `VisionManager` should behave in another
```
[the remark this answers is not in the document]
Comment (IodaMikeMapbox) [reply MapboxVision/Helpers/AssertionFailure.swift]: sure

File: MapboxVision/Helpers/AssertionFailure.swift (hunk 27 above)
[the remark this answers is not in the document]
Comment (IodaMikeMapbox) [reply MapboxVision/Helpers/AssertionFailure.swift]: yeah) thanks

File: MapboxVisionTests/VisionManagerTests.swift (hunk 11 above)
Comment (IodaMikeMapbox) [reply MapboxVisionTests/VisionManagerTests.swift]: I think it's overengineering, we all understand what the test is doing, @chezzdev WDYT?

File: MapboxVisionTests/VisionManagerTests.swift [hunk 34]
```diff
@@ -0,0 +1,139 @@
...
+
+        // Then
+        // Shouldn't be assertion failure
+        MVTAssertNoAssertionFailure(
+            self.visionManager = nil,
+            "VisionManager should be successfully deallocated after calling destroy and releasing the object"
+        )
+    }
+
+    func test_RecordingPermissions() {
```
[the remark this answers is not in the document]
Comment (IodaMikeMapbox) [reply MapboxVisionTests/VisionManagerTests.swift]: ok

File: MapboxVisionTests/VisionManagerTests.swift (hunk 14 above)
Comment (IodaMikeMapbox) [reply MapboxVisionTests/VisionManagerTests.swift]: I think it's redundant, @chezzdev WDYT?

File: MapboxVisionTests/VisionManagerTests.swift (hunk 11 above)
Comment (dersim-davaod) [reply MapboxVisionTests/VisionManagerTests.swift]: Yeah, the test itself is clear.

My point was about comments. If we really need them in order to map the expectations, then I'd move the logic in the code. If I'm wrong and these comments were introduced just as "reminders", then probably it's ok.

Anyway this is no big deal for us and can be treated as nit :)

File: MapboxVisionTests/VisionManagerTests.swift (hunk 14 above)
Comment (chezzdev) [reply MapboxVisionTests/VisionManagerTests.swift]: I guess we're testing "we have expected actions for each case" here and the second point follows from the first one. Comparing arrays tests both cases BTW.

File: MapboxVisionTests/VisionManagerTests.swift (hunk 11 above)
Comment (chezzdev) [reply MapboxVisionTests/VisionManagerTests.swift]: As for me this test does its job and will be rewritten the moment it stops serving its purpose.

File: MapboxVision/VisionManager/VisionManager.swift [hunk 35]
```diff
@@ -227,16 +227,16 @@ public final class VisionManager: BaseVisionManager {
...
         dependencies.recorder.start(mode: mode)
     }
 
     override public func onCountryUpdated(_ country: Country) {
         super.onCountryUpdated(country)
         if country.allowsRecording {
             tryRecording(mode: .internal)
-        } else if dependencies.recorder.currentMode.isInternal {
+        } else if dependencies.recorder.isInternal {
             dependencies.recorder.stop()
```
Comment (chezzdev) [inline MapboxVision/VisionManager/VisionManager.swift]: Here we should call `stop(force: true)`. This bug ins't introduced here and it even shouldn't affect current users since all the telemetry is removed when `China` is detected.
I noticed that when realized that `SessionRecorderProtocol` hides `force` option of `SessionRecorder` method.
This behavior will be adjusted in https://github.com/mapbox/mapbox-vision/issues/1312 so there's no need to change anything. Just putting it here for the record.

File: MapboxVision.xcodeproj/xcshareddata/xcschemes/MapboxVisionTests.xcscheme [hunk 36]
```diff
@@ -0,0 +1,56 @@
+<?xml version="1.0" encoding="UTF-8"?>
```
Comment (dersim-davaod) [inline MapboxVision.xcodeproj/xcshareddata/xcschemes/MapboxVisionTests.xcscheme]: Please hide `MapboxVisionTests` scheme from scheme list.

File: MapboxVisionTests/VisionManagerTests.swift [hunk 37]
```diff
@@ -0,0 +1,137 @@
...
+
+        // Then
+        // we expect that visionManager will call SessionRecorder's method `startInternal` for all countries but China and that there
+        // will no be any other calls to SessionRecorder. For China we expect `stop` method to be called
+        let expectedActions: [MockSessionRecorder.Action] = [
+            .startInternal, // USA
+            .startInternal, // UK
+            .stop,          // China
+            .startInternal, // other
+            .startInternal  // unknown
```
Comment (dersim-davaod) [inline MapboxVisionTests/VisionManagerTests.swift]: Please add a trailing comma. Same below.

File: MapboxVision/VisionManager/VisionManagerNativeProtocol.swift [hunk 38]
```diff
@@ -0,0 +1,35 @@
...
+    func stop()
+
+    func destroy()
+
+    func getSeconds() -> Float
+    func startSavingSession(_ path: String)
+    func stopSavingSession()
+}
+
+extension VisionManagerBaseNative: VisionManagerBaseNativeProtocol {
```
Comment (dersim-davaod) [inline MapboxVision/VisionManager/VisionManagerNativeProtocol.swift]: Move both braces to single line.
```suggestion
extension VisionManagerBaseNative: VisionManagerBaseNativeProtocol {}
```

File: MapboxVisionTests/VisionManagerTests.swift [hunk 39]
```diff
@@ -0,0 +1,137 @@
...
+        )
+
+        self.visionManager = VisionManager(dependencies: dependencies!, videoSource: MockVideoSource())
+    }
+
+    func testNoCrashOnVisionManagerDeallocWithoutDestroy() {
+        // We called destroy in destructors of VisionManager, BaseVisionManager, VisionManagerNative and VisionManagerBaseNative,
+        // so VisionManagerBaseNative's destroy method called multiple times, so we tried to destroy already destroyed resources,
+        // which caused an EXC_BAD_ACCESS.
+
```
Comment (dersim-davaod) [inline MapboxVisionTests/VisionManagerTests.swift]: nit: I would remove that line, but it's not an issue.

File: MapboxVisionTests/VisionManagerTests.swift [hunk 40]
```diff
@@ -0,0 +1,137 @@
...
+            synchronizer: MockSynchronizable(),
+            recorder: MockSessionRecorder(),
+            dataProvider: MockDataProvider(),
+            deviceInfo: DeviceInfoProvider()
+        )
+
+        self.visionManager = VisionManager(dependencies: dependencies!, videoSource: MockVideoSource())
+    }
+
+    func testNoCrashOnVisionManagerDeallocWithoutDestroy() {
```
Comment (dersim-davaod) [inline MapboxVisionTests/VisionManagerTests.swift]: Do we test there's no crash? A bit confusing as I see only checks there's no exception. Here and below.

File: MapboxVisionTests/VisionManagerTests.swift [hunk 41]
```diff
@@ -0,0 +1,137 @@
...
+        // We called destroy in destructors of VisionManager, BaseVisionManager, VisionManagerNative and VisionManagerBaseNative,
+        // so VisionManagerBaseNative's destroy method called multiple times, so we tried to destroy already destroyed resources,
+        // which caused an EXC_BAD_ACCESS.
+
+        // Nevertheless the logic was sort of right, it should do assertFailure on deinit without destroy was called
```
Comment (dersim-davaod) [inline MapboxVisionTests/VisionManagerTests.swift]: Please remove that comment.

Comment (dersim-davaod) [reply MapboxVisionTests/VisionManagerTests.swift]: Could you please review and revision all comments in tests as well?

File: MapboxVisionTests/VisionManagerTests.swift (hunk 40 above)
Comment (IodaMikeMapbox) [reply MapboxVisionTests/VisionManagerTests.swift]: yes, but we can't write explicit test for EXC_BAD_ACCESS

File: MapboxVision.xcodeproj/xcshareddata/xcschemes/MapboxVisionTests.xcscheme (hunk 36 above)
Comment (IodaMikeMapbox) [reply MapboxVision.xcodeproj/xcshareddata/xcschemes/MapboxVisionTests.xcscheme]: ok

File: MapboxVision/VisionManager/VisionManagerNativeProtocol.swift (hunk 38 above)
Comment (IodaMikeMapbox) [reply MapboxVision/VisionManager/VisionManagerNativeProtocol.swift]: done

File: MapboxVisionTests/VisionManagerTests.swift (hunk 39 above)
Comment (IodaMikeMapbox) [reply MapboxVisionTests/VisionManagerTests.swift]: done

File: MapboxVisionTests/VisionManagerTests.swift (hunk 41 above)
Comment (IodaMikeMapbox) [reply MapboxVisionTests/VisionManagerTests.swift]: sure
